### ISSUE TITLE
tag release on quay not working

### ISSUE THREAD

**Issue by pacospace** [thoth-station/aicoe-ci#25]
**Describe the bug**
I tagged v0.1.0-dev for https://github.com/thoth-station/unresolved-package-handler/tree/v0.1.0-dev after making sure the repo on quay was created and correctly set. No release has been created on quay.

**To Reproduce**
1. Go to thoth-station/unresolved-package-handler.
2. Create tag.
3. Wait some time and nothing happen on quay.

**Expected behavior**
A new tag release is created on quay after creating the tag.

**Comment by goern** [comment]
@pacospace is this still valid?

**Comment by pacospace** [comment]
I encountered another issue today with https://quay.io/repository/thoth-station/workflow-helpers?tab=tags

**Comment by harshad16** [comment]
This scenario occurred due to the failure of builds, the failure logs are here:
unresolved-package-handler
```
Installing collected packages: voluptuous
Successfully installed voluptuous-0.11.7
Collecting websocket-client==0.57.0
  Downloading websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Installing collected packages: websocket-client
Successfully installed websocket-client-0.57.0
Collecting yarl==1.4.2
  Downloading yarl-1.4.2-cp36-cp36m-manylinux1_x86_64.whl (252 kB)
Installing collected packages: yarl
Successfully installed yarl-1.4.2
---> Installing application ...
Processing /opt/app-root/src
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/app-root/bin/python3.6 /opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpwwdgwhki
         cwd: /tmp/pip-req-build-s1u7ptk4
    Complete output (10 lines):
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ez32j9uj/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        assert len(dist_infos) == 1
    AssertionError
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/app-root/bin/python3.6 /opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpwwdgwhki Check the logs for full command output.
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1
```

advise-reporter
```
Successfully installed yarl-1.4.2
Collecting zipp==3.1.0
  Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: zipp
Successfully installed zipp-3.1.0
Collecting tangled-up-in-unicode==0.0.6
  Downloading tangled_up_in_unicode-0.0.6-py3-none-any.whl (3.1 MB)
Installing collected packages: tangled-up-in-unicode
Failed to install requirements, dependency 'tangled-up-in-unicode' could not be installed
subprocess exited with status 3
subprocess exited with status 3
error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 3
```

Fixing the pipeline and will check back on these image builds based on tags.
Thanks for opening the issue.

**Comment by fridex** [comment]
We saw these errors with some version of pip. Upgrading it to a more recent version fixed it. Hopefully, it will help...

**Comment by goern** [comment]
is this still valid?

**Comment by pacospace** [comment]
I think it can be closed, I didn't have that problem anymore.
